/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#bfc9c1",
        "surface-container": "#edecff",
        "primary-container": "#2d6a4f",
        "on-tertiary-fixed-variant": "#5e4100",
        "inverse-primary": "#95d4b3",
        "background": "#fbf8ff",
        "surface-tint": "#2c694e",
        "secondary-fixed": "#ffdad8",
        "surface-variant": "#e0e0fc",
        "on-surface": "#181a2e",
        "surface-container-low": "#f4f2ff",
        "on-secondary-fixed-variant": "#861f25",
        "on-secondary-fixed": "#410007",
        "on-tertiary-fixed": "#271900",
        "on-secondary-container": "#74101a",
        "outline": "#707973",
        "on-surface-variant": "#404943",
        "tertiary-fixed": "#ffdea9",
        "on-primary-container": "#a8e7c5",
        "tertiary": "#5f4200",
        "surface-container-lowest": "#ffffff",
        "surface": "#fbf8ff",
        "surface-container-highest": "#e0e0fc",
        "surface-bright": "#fbf8ff",
        "on-error-container": "#93000a",
        "surface-dim": "#d7d8f4",
        "secondary": "#a7373b",
        "secondary-fixed-dim": "#ffb3b0",
        "primary-fixed-dim": "#95d4b3",
        "primary-fixed": "#b1f0ce",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#0e5138",
        "inverse-surface": "#2d2f44",
        "tertiary-fixed-dim": "#ffba27",
        "error-container": "#ffdad6",
        "primary": "#0f5238",
        "tertiary-container": "#7e5800",
        "inverse-on-surface": "#f1efff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e6ff",
        "secondary-container": "#ff7a7a",
        "on-background": "#181a2e",
        "error": "#ba1a1a",
        "on-primary-fixed": "#002114",
        "on-tertiary-container": "#ffd388",
        "on-primary": "#ffffff",
        "on-error": "#ffffff"
      },
      spacing: {
        "gutter-mobile": "12px",
        "stack-sm": "4px",
        "base": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "margin-mobile": "16px"
      }
    },
  },
  plugins: [],
}
